export const words = [
  // 3-letter words
  'sun', 'cat', 'dog', 'ice', 'key', 'owl', 'fox', 'gem', 'web', 'egg', 'big',
  'law', 'mix', 'raw', 'dry', 'fix', 'end', 'oil', 'gas', 'win', 'tie',
  'cut', 'wet', 'far', 'dig', 'run', 'bad', 'pen', 'bag', 'jam', 'lie',

  // 4-letter words
  'fire', 'moon', 'star', 'wind', 'wave', 'gold', 'ruby', 'jade', 'silk', 'mist',
  'wolf', 'bear', 'deer', 'hawk', 'dove', 'rose', 'lily', 'sage', 'mint', 'pine',
  'acid', 'base', 'fall', 'grow', 'lift', 'loud', 'luck', 'melt', 'pair', 'path',
  'ruin', 'safe', 'spin', 'tiny', 'weak', 'wild', 'zero', 'copy', 'cold', 'fast',
  'bank', 'beat', 'calm', 'dark', 'draw', 'drop', 'dull', 'fine', 'fold', 'hike',
  'jump', 'kind', 'leak', 'link', 'rich', 'ring', 'sign', 'sour', 'tall', 'west',

  // 5-letter words
  'forge', 'frost', 'flame', 'storm', 'blade', 'crown', 'ghost', 'witch', 'demon', 'angel',
  'pearl', 'quill', 'scroll', 'relic', 'shard', 'prism', 'lunar', 'solar', 'toxic', 'bloom',
  'drake', 'hydra', 'sphinx', 'titan', 'wraith', 'crypt', 'abyss', 'fjord', 'oasis', 'delta',
  'anvil', 'spear', 'arrow', 'light', 'shade', 'spark', 'blaze', 'ocean', 'river', 'cloud',
  'quake', 'venom', 'thorn', 'scale', 'dream', 'sleep', 'night', 'legend', 'totem',
  'above', 'alone', 'angry', 'begin', 'blank', 'build', 'chain', 'chaos', 'climb', 'close',
  'craft', 'cycle', 'empty', 'error', 'exact', 'extra', 'faint', 'false', 'giant', 'guard',
  'guess', 'heavy', 'image', 'layer', 'limit', 'liquid', 'loose', 'match', 'metal', 'noise',
  'order', 'outer', 'party', 'piece', 'plain', 'prize', 'punch', 'ready', 'round', 'royal',
  'score', 'shake', 'sharp', 'solid', 'split', 'stuck', 'think', 'track',
  'alarm', 'alive', 'awake', 'brave', 'break', 'brief', 'bright', 'catch', 'cheap', 'chili',
  'clear', 'coast', 'combo', 'crash', 'crisp', 'cross', 'crush', 'dirty', 'draft', 'dress',
  'drive', 'field', 'final', 'float', 'fresh', 'front', 'green', 'grill', 'joker', 'leave',
  'level', 'light', 'local', 'lousy', 'model', 'north', 'other', 'point', 'press', 'quest',
  'raise', 'scale', 'sense', 'throw', 'tough', 'trade', 'train', 'watch',

  // 6-letter words
  'dragon', 'wizard', 'castle', 'forest', 'temple', 'mystic', 'potion', 'crystal', 'shadow', 'spirit',
  'across', 'ancient', 'balance', 'bottom', 'connect', 'danger', 'future', 'memory', 'secret', 'shrink',
  'abroad', 'answer', 'beauty', 'camera', 'circle', 'double', 'energy', 'follow', 'makeup', 'strong'
];

// Emoji hints for each word
export const emojiHints: Record<string, string[]> = {
  // Original Set: 3-letter words
  'sun': ['☀️', '🌅', '😎'],
  'cat': ['🐱', '🧶', '🐟'],
  'dog': ['🐕', '🦴', '🎾'],
  'ice': ['🧊', '🥶', '🐧'],
  'key': ['🗝️', '🚪', '🔓'],
  'owl': ['🦉', '🌙', '🌳'],
  'fox': ['🦊', '🌲', '🐔'],
  'gem': ['💎', '💍', '👑'],
  'web': ['🕸️', '🕷️', '🌐'],
  'egg': ['🥚', '🐣', '🍳'],
  'big': ['🐘','🐋', '🦖'],

  // New Sets: 3-letter words
  'law': ['🧑‍⚖️', '📜', '🏛️'],
  'mix': ['🎨', '🥣', '🔀'],
  'raw': ['🥩', '🥕', '🍣'],
  'dry': ['🏜️', '🥵', '👕'],
  'fix': ['🔧', '🩹', '⚙️'],
  'end': ['🏁', '🔚', '🛑'],
  'oil': ['🛢️', '🍳', '🎨'],
  'gas': ['⛽', '💨', '🎈'],
  'win': ['🏆', '🥇', '🎉'],
  'tie': ['👔', '🎀', '🟰'],
  'cut': ['✂️', '🔪', '🪓'],
  'wet': ['💧', '🏊‍♀️', '🌧️'],
  'far': ['🔭', '↔️', '🌌'],
  'dig': ['⛏️', '🐕', '🥕'],
  'run': ['🏃‍♀️', '💧', '🐆'],
  'bad': ['👎', '😈', '🍎'],
  'pen': ['🖊️', '🐷', '✍️'],
  'bag': ['🛍️', '🎒', '💰'],
  'jam': ['🍓', '🚗🚙', '🎸'],
  'lie': ['🤥', '🛌', '❌'],

  // Original Set: 4-letter words
  'fire': ['🔥', '🪵', '🏕️'],
  'moon': ['🌙', '🌕', '🌊'],
  'star': ['⭐', '🔭', '🌌'],
  'wind': ['💨', '🍃', '🪁'],
  'wave': ['🌊', '🏄‍♀️', '🏖️'],
  'gold': ['🪙', '👑', '🥇'],
  'ruby': ['💎', '❤️', '💍'],
  'jade': ['💚', '🗿', '📿'],
  'silk': ['🐛', '🧵', '👘'],
  'mist': ['🌫️', '💧', '🌉'],
  'wolf': ['🐺', '🐾', '🌕'],
  'bear': ['🐻', '🍯', '🏞️'],
  'deer': ['🦌', '🌲', '👣'],
  'hawk': ['🦅', '👁️', '🐁'],
  'dove': ['🕊️', '🌿', '☮️'],
  'rose': ['🌹', '👃', '🌵'],
  'lily': ['🌸', '🌿', '🐸'],
  'sage': ['🌿', '🔥', '🌬️'],
  'mint': ['🌿', '🍵', '🍬'],
  'pine': ['🌲', '🪵', '🏔️'],

  // New Sets: 4-letter words
  'acid': ['🍋', '🧪', '⚠️'],
  'base': ['⚾', '🏕️', '🎸'],
  'fall': ['🍂', '🤸‍♂️', '🌊'],
  'grow': ['🌱', '📈', '📏'],
  'lift': ['🏋️‍♀️', '🎈', '🚜'],
  'loud': ['📢', '🔊', '💥'],
  'luck': ['🍀', '🎲', '🤞'],
  'melt': ['🫠', '🧊➡️💧', '🕯️'],
  'pair': ['🍐', '👟', '🧑‍🤝‍🧑'],
  'path': ['🚶‍♀️', '↔️', '🌲'],
  'ruin': ['🏚️', '🏛️', '💥'],
  'safe': ['🔒', '✅', '🏦'],
  'spin': ['🌪️', '💿', '🎡'],
  'tiny': ['🐜', '🔬', '🤏'],
  'weak': ['😫', '🪫', '🤧'],
  'wild': ['🦁', '🌴', '🏞️'],
  'zero': ['0️⃣', '🚫', '🤷'],
  'copy': ['📠', '👯', '🦜'],
  'cold': ['🥶', '🐧', '🍦'],
  'fast': ['🐆', '🏎️', '🚀'],
  'bank': ['🏦', '💵', '🏞️'],
  'beat': ['🥁', '❤️', '🥇'],
  'calm': ['🧘‍♀️', '🌊', '🍵'],
  'dark': ['🌑', '🕶️', '🦇'],
  'draw': ['✏️', '🃏', '🰰'],
  'drop': ['💧', '🎤', '⬇️'],
  'dull': ['🥱', '🥄', '灰色'],
  'fine': ['👌', '💸', '☀️'],
  'fold': ['🗂️', '🙌', '🃏'],
  'hike': ['🥾', '🎒', '🏔️'],
  'jump': ['🤸‍♀️', '🐸', '📈'],
  'kind': ['🤗', '🎁', '💖'],
  'leak': ['💧', '🤫', '📰'],
  'link': ['🔗', '🌭', '🌐'],
  'rich': ['💰', '💎', '🍫'],
  'ring': ['💍', '🔔', '🪐'],
  'sign': ['🪧', '✍️', '♎'],
  'sour': ['🍋', '😒', '🍬'],
  'tall': ['🦒', '🏢', '🌲'],
  'west': ['⬅️', '🤠', '🌇'],

  // Original Set: 5-letter words
  'forge': ['🔥', '🔨', '⚔️'],
  'frost': ['❄️', '🥶', '🪟'],
  'flame': ['🕯️', '🔥', '♨️'],
  'storm': ['⛈️', '⚡', '⛵'],
  'blade': ['⚔️', '🗡️', '🔪'],
  'crown': ['👑', '🤴', '💎'],
  'ghost': ['👻', '⛓️', '🏰'],
  'witch': ['🧙‍♀️', '🧹', '⚗️'],
  'demon': ['😈', '🔥', '🔱'],
  'angel': ['👼', '😇', '☁️'],
  'pearl': ['🦪', '⚪', '📿'],
  'quill': ['🪶', '✒️', '📜'],
  'scroll': ['📜', '🗺️', '✍️'],
  'relic': ['🏺', '🦴', '⏳'],
  'shard': ['💔', '🏺', '💎'],
  'prism': ['🌈', '💎', '💡'],
  'lunar': ['🌙', '🌑', '🌊'],
  'solar': ['☀️', '🌻', '🔋'],
  'toxic': ['☠️', '🧪', '☣️'],
  'bloom': ['🌱', '🌿', '🌸'],
  'drake': ['🐉', '🔥', '🪙'],
  'hydra': ['🐉', '💧', '👥'],
  'sphinx': ['🦁', '❓', '🏜️'],
  'titan': ['⚡', '🌋', '💪'],
  'wraith': ['👻', '😱', '🌫️'],
  'crypt': ['⚰️', '🪦', '🏛️'],
  'abyss': ['🕳️', '⬇️', '❓'],
  'fjord': ['🏔️', '🌊', '🛶'],
  'oasis': ['🌴', '💧', '🏜️'],
  'delta': ['🔺', '🏞️', '🌊'],
  'anvil': ['🔨', '🔥', '🛡️'],
  'spear': ['🔱', '🎯', '🐟'],
  'arrow': ['🏹', '🎯', '🪶'],
  'light': ['🪶', '💡', '🎨'],
  'shade': ['🌳', '🕶️', '⛱️'],
  'spark': ['⚡', '💥', '⚙️'],
  'blaze': ['🔥', '🚒', '🏢'],
  'ocean': ['🌊', '🐋', '🚢'],
  'river': ['🏞️', '🛶', '🐟'],
  'cloud': ['☁️', '🌧️', '✈️'],
  'quake': ['🌍', '〰️', '🏚️'],
  'venom': ['🐍', '☠️', '🩸'],
  'thorn': ['🌹', '🌵', '🩹'],
  'scale': ['⚖️', '🧗‍♀️', '🐟'],
  'dream': ['😴', '💭', '🦄'],
  'sleep': ['😴', '🛏️', '💤'],
  'night': ['🌃', '🦉', '⭐'],
  'legend': ['👑', '⚔️', '📖'],
  'totem': ['🗿', '🦅', '🐻'],

  // New Sets: 5-letter words
  'above': ['☁️', '⬆️', '✈️'],
  'alone': ['👤', '🏝️', '🏠'],
  'angry': ['😡', '😤', '🗯️'],
  'begin': ['🌅', '🌱', '▶️'],
  'blank': ['📄', '⬜', '❓'],
  'build': ['🧱', '🏗️', '🟥'],
  'chain': ['🔗', '⛓️', '🚲'],
  'chaos': ['🤯', '💥', '〰️'],
  'climb': ['🧗‍♀️', '🪜', '📈'],
  'close': ['🚪', '🤐', '↔️'],
  'craft': ['✂️', '🧶', '🛶'],
  'cycle': ['🔄', '🚲', '🍂❄️🌸'],
  'empty': ['🫙', '⛽', '💭'],
  'error': ['❌', '🤖', '👾'],
  'exact': ['🎯', '📍', '✔️'],
  'extra': ['➕', '²⁺', '🎁'],
  'faint': ['😵', '🤫', '🌫️'],
  'false': ['🤥', '❌', '🎭'],
  'giant': ['巨人', '👣', '🦒'],
  'guard': ['💂', '🛡️', '🐕'],
  'guess': ['❓', '🤔', '🤷‍♀️'],
  'heavy': ['🐘', '🏋️‍♀️', '🧱'],
  'image': ['🖼️', '📷', '🏞️'],
  'layer': ['🧅', '🎂', '겹침'],
  'limit': ['🛑', '🚧', '🚫'],
  'liquid': ['💧', '🌊', '🥤'],
  'loose': ['👖', '🔩', '🦷'],
  'match': ['🔥', '⚽', '👯'],
  'metal': ['🪙', '⛓️', '🤖'],
  'noise': ['💥', '📢', '🚧'],
  'order': ['📦', '🧑‍⚖️', '🍔'],
  'outer': ['🪐', '👽', '🚀'],
  'party': ['🎉', '🎈', '🥳'],
  'piece': ['🧩', '🍰', '♟️'],
  'plain': ['✈️', '🍞', '⬜'],
  'prize': ['🏆', '🥇', '🎁'],
  'punch': ['🥊', '🥤', '👊'],
  'ready': ['✅', '👍', '🚦'],
  'round': ['🌎', '💿', '🍪'],
  'royal': ['👑', '🏰', '⚜️'],
  'score': ['💯', '⚽', '🎼'],
  'shake': ['🤝', '🥤', '🧂'],
  'sharp': ['🔪', '🌵', '🧠'],
  'solid': ['🪨', '🧱', '🧊'],
  'split': ['↔️', '🍌', '✂️'],
  'stuck': ['🍯', '🚗🚙🚕', '🕸️'],
  'think': ['🤔', '💡', '🧠'],
  'track': ['🐾', '🚂', '🏃‍♀️'],
  'alarm': ['⏰', '🔔', '🚨'],
  'alive': ['❤️‍🩹', '🌱', '⚡'],
  'awake': ['👀', '☕', '☀️'],
  'brave': ['🦁', '🧑‍🚒', '🛡️'],
  'break': ['💔', '☕', '🥚'],
  'brief': ['🩲', '💼', '⏳'],
  'bright': ['💡', '☀️', '🧠'],
  'catch': ['⚾', '🎣', '🤧'],
  'cheap': ['🏷️', '🐦', '📉'],
  'chili': ['🌶️', '🥶', '🍲'],
  'clear': ['💎', '✅', '🪟'],
  'coast': ['🏖️', '➡️', '🌊'],
  'combo': ['🥊', '🥨+🧀', '🔑'],
  'crash': ['💥', '🚗', '😴'],
  'crisp': ['🥓', '💵', '🍂'],
  'cross': ['✝️', '😡', '🚶‍♀️'],
  'crush': ['🍇', '❤️‍🔥', '🚗'],
  'dirty': ['🐷', '🗑️', '🧺'],
  'draft': ['🍺', '🌬️', '✍️'],
  'dress': ['👗', '🥗', '🩹'],
  'drive': ['🚗', '💾', '⛳'],
  'field': ['🏈', '🏞️', '🛡️'],
  'final': ['🏁', '🏆', '💯'],
  'float': ['🎈', '🍦', '🏊‍♀️'],
  'fresh': ['🌿', '✨', '🍞'],
  'front': ['🏠', '➡️', '🎭'],
  'green': ['🐸', '🍀', '💵'],
  'grill': ['🥩', '☀️', '🦷'],
  'joker': ['🃏', '🤡', '🤣'],
  'leave': ['👋', '🍂', '🌳'],
  'level': ['🎚️', '📏', '🍄'],
  'local': ['🏘️', '🧑‍🌾', '🚂'],
  'lousy': ['👎', '🐜', '🤒'],
  'model': ['💃', '🚗', '🏰'],
  'north': ['⬆️', '🐻‍❄️', '🧭'],
  'other': ['🤷‍♀️', '↔️', '👽'],
  'point': ['📍', '✏️', '👉'],
  'press': ['📰', '🏋️‍♀️', '☕'],
  'quest': ['🗺️', '⚔️', '❓'],
  'raise': ['🙋‍♀️', '📈', '🪙'],
  'sense': ['👃', '👁️', '👂'],
  'throw': ['⚾', '🗑️', '🎉'],
  'tough': ['💪', '🥩', '💎'],
  'trade': ['🤝', '🔄', '📈'],
  'train': ['🚂', '🏋️‍♀️', '🐕'],
  'watch': ['⌚', '👀', '🌊'],

  // Original Set: 6-letter words
  'dragon': ['🐉', '🔥', '🏰'],
  'wizard': ['🧙‍♂️', '🪄', '📖'],
  'castle': ['🏰', '👑', '🛡️'],
  'forest': ['🌲', '🐻', '🧭'],
  'temple': ['🏛️', '🙏', '🔔'],
  'mystic': ['🔮', '👁️', '🌌'],
  'potion': ['🧪', '❤️', '💪'],
  'crystal': ['💎', '🔮', '⛏️'],
  'shadow': ['👤', '🔦', '☀️'],
  'spirit': ['👻', '🥃', '🌬️'],

  // New Sets: 6-letter words
  'across': ['↔️', '🌉', '🚶‍♀️'],
  'ancient': ['🏺', '📜', '🦖'],
  'balance': ['⚖️', '🧘‍♀️', '☯️'],
  'bottom': ['⬇️', '⚓', '🍑'],
  'connect': ['🔗', '🔌', '🤝'],
  'danger': ['⚠️', '⚡', '🦈'],
  'future': ['🤖', '🔮', '🚀'],
  'memory': ['🧠', '🐘', '💾'],
  'secret': ['🤫', '🤐', '🗝️'],
  'shrink': ['🤏', '🔬', '🧺'],
  'abroad': ['✈️', '🌍', '🧳'],
  'answer': ['🙋‍♀️', '✅', '🗣️'],
  'beauty': ['💅', '🌹', '🌅'],
  'camera': ['📷', '🎞️', '🖼️'],
  'circle': ['⭕', '🔄', '🤝'],
  'double': ['👯', '✌️', '🍔'],
  'energy': ['⚡', '💪', '🏃‍♀️'],
  'follow': ['👣', '➡️', '🐑'],
  'makeup': ['💄', '💅', '🤝'],
  'strong': ['💪', '🏋️‍♀️', '🌶️'],
};